Fix race causing futures to be forgotten too early
We were using multiple .done() checks as a condition for processing a
group of futures and then deleting them from the dict. The problem is
that futures can finish right after a .wait(), meaning they would be
.done() but not yet in `done_futures`. Instead they'd surprise us by
being in `done_futures` after the next .wait(), leading to the error:

  File "__init__.py", line 607, in process_recursive
    other_dir_futures, _ = futures[done_future]
KeyError: <Future at 0x7fbfe041adf0 state=finished returned tuple>